spring.config.import=optional:file:.env[.properties]

spring.application.name=obvx

# ===============================
# DATABASE MYSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/obvx-admin
spring.datasource.username=${DB_username}
spring.datasource.password=${DB_password}


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}